ToDone/Models/Task.cs
namespace ToDone.Models
{
    using System;

    public class Task
    {
        public Task(string name)
        {
            Id = Guid.NewGuid();
            Name = name;
            CreatedAt = DateTime.Now;
        }

        public Guid Id { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public DateTime CreatedAt { get; set; }
        public bool Completed { get; set; }
    }
}

ToDone/Controllers/TaskController.cs
namespace ToDone.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;
    using Models;

    public class TaskController : Controller
    {
        //TODO: MongoDB
        private static List<Task> _tasks = new List<Task>
        {
            new Task("Homework") { CreatedAt = new DateTime(2014, 10, 24, 13, 45, 58), Number = 1 },
            new Task("Book") { CreatedAt = new DateTime(2015, 1, 14, 16, 46, 22), Number = 2 },
            new Task("Clean") { CreatedAt = new DateTime(2015, 2, 5, 5, 56, 12), Number = 3 }
        };

        public ActionResult Index()
        {
            return View(_tasks);
        }

        public ActionResult Create(string name)
        {
            _tasks.Add(new Task(name));

            return PartialView("Partials/TodoList", _tasks);
        }

        public EmptyResult Delete(Guid id)
        {
            _tasks.Remove(_tasks.Find(x => x.Id == id));

            return null;
        }
    }
}

ToDone/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

@{

}

<head>
    <title>ToDone: Simple todo list application</title>

    @Styles.Render("~/Content/bootstrap/less")
    @Styles.Render("~/Content/less")
    @Scripts.Render("~/Scripts/knockout")
    @Scripts.Render("~/Scripts/jquery")
    @Scripts.Render("~/Scripts/site")
</head>
<body>
    @RenderBody()
    @RenderSection("scripts", false)
</body>

ToDone/Views/Task/Index.cshtml
@model IEnumerable<ToDone.Models.Task>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 class="text-center">Tasks</h2>

<div>
    @using (Ajax.BeginForm("Create", "Task", new AjaxOptions { UpdateTargetId = "todoList", OnComplete = "addComplete" }, new { @class = "form-inline text-center" }))
    {
        <input id="inputNewTask" type="text" name="name" class="form-control" placeholder="Task" />
        <button type="submit" class="btn-primary">Add</button>
    }

    @Html.Partial("Partials/TodoList")
</div>

ToDone/Views/Task/Partials/TodoList.cshtml
@model IEnumerable<ToDone.Models.Task>

<div class="row" id="todoList">
    <div class="col-md-6 col-md-offset-3">
        <table class="table table-content-center" data-bind="visible: todoList().length > 0">
            <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Number)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CreatedAt)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Completed)
                </th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            @{
                var i = 1;
                foreach (var item in Model)
                {
                    <tr>
                        <td>@i</td>
                        <td><input class="form-control text-center" value="@item.Name"/></td>
                        <td>@item.CreatedAt</td>
                        <td><input type="checkbox"/></td>
                        <td>@Ajax.ActionLink("Delete", "Delete", new {id = @item.Id}, new AjaxOptions
                            {
                                Confirm = "Do you want to delete?",
                                OnComplete = "deleteComplete",
                                HttpMethod = "DELETE"

                            })</td>
                    </tr>
                    i++;
                }
            }
            </tbody>
        </table>
    </div>
</div>